//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dugun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DugunSalonu
    {
        public DugunSalonu()
        {
            this.Dugun = new HashSet<Dugun>();
            this.User = new HashSet<User>();
        }
    
        public int DugunSalonuID { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public Nullable<decimal> TelNo { get; set; }
        public Nullable<System.DateTime> DtInsert { get; set; }
        public Nullable<System.DateTime> DtUpdate { get; set; }
        public Nullable<int> RowStatus { get; set; }
    
        public virtual ICollection<Dugun> Dugun { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}
