//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dugun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dugun
    {
        public Dugun()
        {
            this.Table = new HashSet<Table>();
            this.User = new HashSet<User>();
            this.Guest = new HashSet<Guest>();
            this.Service = new HashSet<Service>();
        }
    
        public int DugunID { get; set; }
        public int DugunSalonuID { get; set; }
        public string Name { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public int PersonCount { get; set; }
        public Nullable<System.DateTime> DtInsert { get; set; }
        public Nullable<System.DateTime> DtUpdate { get; set; }
        public Nullable<int> RowStatus { get; set; }
    
        public virtual ICollection<Table> Table { get; set; }
        public virtual DugunSalonu DugunSalonu { get; set; }
        public virtual ICollection<User> User { get; set; }
        public virtual ICollection<Guest> Guest { get; set; }
        public virtual ICollection<Service> Service { get; set; }
    }
}
